------------------------------------------------(PART-A)-------------------------------------------------------
---CREATING SALES_DATA TABLE

CREATE TABLE SALES_DATA(
REGION VARCHAR(50),
PRODUCT VARCHAR(50),
SALES_AMOUNT INT,
YEAR DATETIME
);

INSERT INTO SALES_DATA VALUES('North America','Watch',1500,'2023');
INSERT INTO SALES_DATA VALUES('Europe','Mobile',1200,'2023');
INSERT INTO SALES_DATA VALUES('Asia','Watch',1800,'2023');
INSERT INTO SALES_DATA VALUES('North America','TV',900,'2024');
INSERT INTO SALES_DATA VALUES('Europe','Watch',2000,'2024');
INSERT INTO SALES_DATA VALUES('Asia','Mobile',1000,'2024');
INSERT INTO SALES_DATA VALUES('North America','Mobile',1600,'2023');
INSERT INTO SALES_DATA VALUES('Europe','TV',1500,'2023');
INSERT INTO SALES_DATA VALUES('Asia','TV',1100,'2024');
INSERT INTO SALES_DATA VALUES('North America','Watch',1700,'2024');


SELECT*FROM SALES_DATA


---Display Total Sales Amount by Region
SELECT  REGION,SUM(SALES_AMOUNT) AS UPDATED_DATA   FROM SALES_DATA GROUP BY REGION

---Display Average Sales Amount by Product
SELECT AVG(SALES_AMOUNT) AS UPDATED_AMOUNT FROM SALES_DATA GROUP BY PRODUCT

---Display Maximum Sales Amount by Year
SELECT YEAR, MAX(SALES_AMOUNT) AS UPDATED_AMOUNT FROM SALES_DATA GROUP BY YEAR

---Display Minimum Sales Amount by Region and Year
SELECT REGION,YEAR,MIN(SALES_AMOUNT) AS UPDATED_AMOUNT FROM SALES_DATA GROUP BY REGION,YEAR

---Count of Products Sold by Region
SELECT REGION,COUNT(PRODUCT) AS SOLD_PRODUCT FROM SALES_DATA GROUP BY REGION

---Display Sales Amount by Year and Product
SELECT COUNT(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA GROUP BY YEAR,PRODUCT

---Display Regions with Total Sales Greater Than 5000
SELECT REGION,COUNT(SALES_AMOUNT) AS UP_SALE FROM SALES_DATA GROUP BY REGION HAVING COUNT(SALES_AMOUNT)>5000

---Display Products with Average Sales Less Than 10000
SELECT PRODUCT,AVG(SALES_AMOUNT)AS UP_SALES FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT)<10000

---Display Years with Maximum Sales Exceeding 500
SELECT YEAR,MAX(SALES_AMOUNT) AS UP_SALES FROM SALES_DATA GROUP BY YEAR HAVING MAX(SALES_AMOUNT)>500

---Display Regions with at Least 3 Distinct Products Sold.
SELECT REGION,COUNT(DISTINCT PRODUCT) AS UP_DATA FROM SALES_DATA GROUP BY REGION HAVING COUNT(DISTINCT PRODUCT)=3

---Display Years with Minimum Sales Less Than 1000
SELECT YEAR,MIN(SALES_AMOUNT) AS UPDATED_SALES FROM SALES_DATA HAVING MIN(SALES_AMOUNT)<1000

---Display Total Sales Amount by Region for Year 2023, Sorted by Total Amount
SELECT REGION,SUM(SALES_AMOUNT) AS TOTAL_AMOUNT FROM SALES_DATA WHERE YEAR = '2023' GROUP BY REGION ORDER BY SUM(SALES_AMOUNT)


------------------------------------------------------------------PART-B-----------------------------------------------------------------------

---Display Count of Orders by Year and Region, Sorted by Year and Region
SELECT YEAR,REGION ,COUNT(PRODUCT) AS UP_DATA FROM SALES_DATA GROUP BY  YEAR,REGION  ORDER BY  YEAR,REGION 

---Display Regions with Maximum Sales Amount Exceeding 1000 in Any Year, Sorted by Region
SELECT REGION,YEAR,MAX(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA GROUP BY REGION,YEAR HAVING MAX(SALES_AMOUNT)>1000 ORDER BY REGION

---Display Years with Total Sales Amount Less Than 1000, Sorted by Year Descending
SELECT YEAR,SUM(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT)<1000 ORDER BY YEAR DESC

---Display Top 3 Regions by Total Sales Amount in Year 2024
SELECT TOP 3 REGION,SUM(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA WHERE YEAR='2024' GROUP BY REGION


------------------------------------------------------------------PART-C-----------------------------------------------------------------------
---Display Products with Average Sales Amount Between 1000 and 2000, Ordered by Product Name
SELECT PRODUCT,AVG(SALES_AMOUNT) AS UP_DATA FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000
 
---Display Years with More Than 5 Orders from Each Region
SELECT REGION,YEAR AS UP_DATA,COUNT(PRODUCT) FROM SALES_DATA GROUP BY REGION,YEAR HAVING COUNT(PRODUCT)>5

---Display Regions with Average Sales Amount Above 1500 in Year 2023 sort by amount in descending.
SELECT REGION,AVG(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA WHERE YEAR='2023' GROUP BY REGION HAVING AVG(SALES_AMOUNT)>1500 ORDER BY AVG(SALES_AMOUNT) DESC

---Find out region wise duplicate product.
SELECT REGION,PRODUCT, COUNT(PRODUCT) AS UP_DATA FROM SALES_DATA  GROUP BY REGION,PRODUCT HAVING COUNT(PRODUCT)>1

---Find out region wise highest sales amount.

SELECT REGION,MAX(SALES_AMOUNT) AS UP_AMOUNT FROM SALES_DATA GROUP BY REGION

